### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by Adamm00**
Converted spaces to tabs & fix formatting
POSIX Compliance
Fixed weird if statement quirks
- Converted "! -z" to "-n"
- Better number validation method
- Removed multiple cases of bad logic where command output is compared to a value rather then the process exit code

Fixed logic where stubby wouldn't be killed if multiple process exist
Use grep -q where applicable
Use echo in _some_ cases where "extra" string manipulation isn't needed to simplify reading code
Fix logger quoting
Fix var quoting
Remove useless printf
Remove useless entware version checks
Add .gitattributes to force unix line ending

### CODE REVIEW

**Comment by jackyaz** [comment]
@Adamm00 I will pull these changes to my fork, since it seems to be more permanent than initially intended!

**Comment by Adamm00** [comment]
I had a look at your changes in regards to HND support, I personally think the best coarse of action is to merge them to prevent fragmentation, then continue to update the ipk files on the main repo via pull requests until entware pick them up accordingly.

**Comment by jackyaz** [comment]
I agree, but my initial PR went ignored so the fork is seemingly living on for now...

**Comment by jackyaz** [comment]
My fork has pulled in your changes now @Adamm00 :)

**Comment by jackyaz** [comment]
@Adamm00 I'm happy for you to commit directly to my fork...

**Comment by Adamm00** [comment]
The issue is with git limitations and my current workflow (this is mostly untested so-far as I am doing passes over the script making improvements where applicable). I'll let you know when its ready for prime time and it can be merged accordingly as I have no intentions to support it outside of a one time update.

**Comment by jackyaz** [comment]
OK - chuck me a PR when ready and I'll give it a run through

**Comment by Adamm00** [comment]
It does now, lol

**Comment by jackyaz** [comment]
Confused me when I first tried, couldn't figure out why it was downloading a tiny file! Thanks

**Comment by Adamm00** [comment]
Did you end up testing the config changes on a non-hnd device? I only have an AX88U/AC86U. If its an issue I can code a workaround pretty easily or we could even host static binaries for other devices.

**Comment by jackyaz** [comment]
I only have access to an 86U. I'll find a willing volunteer from the forum?

**Comment by Adamm00** [comment]
It’s fine I’ll code a workaround when I get home, besides that everything else seems to work

**Comment by Xentrk** [comment]
I'm back online now. I'll start reviewing and merging the changes tomorrow.  Thank you for collaborating on the project.

**Review by Xentrk — COMMENTED** [review]
https://github.com/Xentrk/Stubby-Installer-Asuswrt-Merlin/pull/3/commits/73b2b10dac54acf60ac2479de0362d6cc3f63f2b

I noticed you changed the printf to echo. I standardized on "printf" rather than "echo" to be POSIX compliant. When I run the code thru the script checker https://www.shellcheck.net/, it complains about using echo. I recall having a conversation with @thelonelycoder on this awhile back and believe that is the direction he took.  What is your concern with printf?

**Comment by Adamm00** [comment]
"echo" is fine, "echo -e" is the issue as it is not POSIX compliant.

As for printf vs echo, it's down to personal preference and coding style, but for readability sake if a string doesn't need extra manipulation I prefer to use echo.

**Comment by Xentrk** [comment]
I found an interesting discussion on the topic here: https://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo

I did spend time going thru the code changes. I need to start fresh tomorrow though as this is my first day back on my feet.  Thanks again for enhancing the installer script.

**Comment by jackyaz** [comment]
If you like, you can add Adam and I as contributors?

**Comment by Xentrk** [comment]
> 
> 
> If you like, you can add Adam and I as contributors?

I sure will.

**Pull request merged**
